{{- range split .availability_zones "," -}}
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ $.cluster_name }}
  name: master-{{ . }}
spec:
  additionalSecurityGroups:
  - {{ $.extra_master_security_group_id }}
  associatePublicIp: false
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-07-28
  machineType: {{ $.master_instance_type }}
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - {{ . }}
{{ end }}
