apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ .cluster_name }}
  name: master-eu-west-1a
spec:
  additionalSecurityGroups:
  - {{ .extra_master_security_group_id }}
  associatePublicIp: false
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.small
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-1a


---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ .cluster_name }}
  name: master-eu-west-1b
spec:
  additionalSecurityGroups:
  - {{ .extra_master_security_group_id }}
  associatePublicIp: false
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.small
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-1b


---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ .cluster_name }}
  name: master-eu-west-1c
spec:
  additionalSecurityGroups:
  - {{ .extra_master_security_group_id }}
  associatePublicIp: false
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.small
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-1c
