apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ .cluster_name }}
  name: nodes
spec:
  additionalSecurityGroups:
  - {{ .extra_node_security_group_id }}
  associatePublicIp: false
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-07-28
  machineType: {{ .node_instance_type }}
  maxSize: {{ .num_nodes }}
  minSize: {{ .num_nodes }}
  role: Node
  rootVolumeSize: 100
  subnets:
{{- range split .private_subnets "," -}}
  {{- $id_and_zone := split . "=" }}
  - {{ index $id_and_zone 1 }}
{{- end -}}
