apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  namespace: kube-system
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        kubernetes.io/cluster-service: "true"
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: elasticsearch_host
          - name:  FLUENT_ELASTICSEARCH_PORT
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: elasticsearch_port
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
