apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  namespace: kube-system
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
type: Opaque
data:
  elasticsearch_host: {{ .Values.elasticsearch.host | b64enc | quote }}
  elasticsearch_port: {{ .Values.elasticsearch.port | b64enc | quote }}
  elasticsearch_scheme: {{ .Values.elasticsearch.scheme | b64enc | quote }}
  elasticsearch_logstash_prefix: {{ .Values.elasticsearch.logstash_prefix | b64enc | quote }}
  {{ if .Values.elasticsearch.username }}
  elasticsearch_username: {{ .Values.elasticsearch.username | b64enc | quote }}
  {{ end }}
  {{ if .Values.elasticsearch.password }}
  elasticsearch_password: {{ .Values.elasticsearch.password | b64enc | quote }}
  {{ end }}
