apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  namespace: kube-system
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
type: Opaque
data:
  elasticsearch_host: {{ .Values.elasticsearch.host | b64enc | quote }}
  elasticsearch_port: {{ .Values.elasticsearch.port | b64enc | quote }}
