kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-home
  annotations:
    volume.beta.kubernetes.io/storage-class: efs
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      mountpoint: "/{{.Username}}"
  resources:
    requests:
      storage: 10Gi
