apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  elasticsearch_host: {{ .Values.elasticsearch.host | b64enc | quote }}
  elasticsearch_port: {{ .Values.elasticsearch.port | b64enc | quote }}
  older_than_days: {{ .Values.curator.older_than_days | b64enc | quote }}
