apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
      annotations:
        checksum/fluentd-config: {{ include (print $.Template.BasePath "/fluentd-configmap.yaml") . | sha256sum }}
    spec:
      containers:

        - name: rstudio-auth-proxy
          image: "{{ .Values.AuthProxy.Image.Repository }}:{{ .Values.AuthProxy.Image.Tag }}"
          imagePullPolicy: {{ .Values.AuthProxy.Image.PullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: USER
              value: {{ .Values.Username }}
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: client_secret
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: client_id
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: domain
            - name: AUTH0_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: callback_url
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: cookie_secret
            - name: SHINY_HOST
              value: localhost
            - name: SHINY_PORT
              value: "8787"
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5

        - name: fluentd
          image: "{{ .Values.Fluentd.Image.Repository }}:{{ .Values.Fluentd.Image.Tag }}"
          imagePullPolicy: {{ .Values.Fluentd.Image.PullPolicy }}
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}-fluentd
                  key: elasticsearch_host
            - name:  FLUENT_ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}-fluentd
                  key: elasticsearch_port
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
            - name: varlogrstudioserver
              mountPath: /var/log/rstudio-server

        - name: r-studio-server
          image: "{{ .Values.RStudio.Image.Repository }}:{{ .Values.RStudio.Image.Tag }}"
          imagePullPolicy: {{ .Values.RStudio.Image.PullPolicy }}
          ports:
            - name: http
              containerPort: 8787
          env:
            - name: USER
              value: {{ .Values.Username }}
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: aws_default_region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: aws_secret_access_key
            - name: TOOLS_DOMAIN
              value: {{ .Values.ToolsDomain }}
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: home
              mountPath: "/home/{{ .Values.Username }}"
            - name: varlogrstudioserver
              mountPath: /var/log/rstudio-server

      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: nfs-home
        - name: varlogrstudioserver
          emptyDir: {}
        - name: fluentd-config
          configMap:
            name: {{ template "fullname" . }}-fluentd
            items:
            - key: fluent.conf
              path: fluent.conf
