apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: "{{ template "fullname" . }}-fluentd"
data:
  fluent.conf: |
    <source>
      @type tail
      format none
      path /var/log/rstudio-server/rserver-http-access.log
      tag "#{ENV['USER']}.rstudio.access"
    </source>

    <source>
      @type tail
      path /var/log/rstudio-server/rserver-http-error.log
      format none
      tag "#{ENV['USER']}.rstudio.error"
    </source>

    <match **>
       type elasticsearch
       log_level info
       include_tag_key true
       host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
       port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
       logstash_format true
       buffer_chunk_limit 2M
       buffer_queue_limit 32
       flush_interval 5s
       max_retry_wait 30
       disable_retry_limit
       num_threads 8
    </match>
