apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: r-studio
  labels:
    app: r-studio
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.Username }}-rstudio.{{ .Values.ToolsDomain }}
    http:
      paths:
      - backend:
          serviceName: r-studio
          servicePort: 80
        path: /
