apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
spec:
  sessionAffinity: ClientIP
  selector:
    app: "{{ .Chart.Name }}"
  ports:
  - port: 80
    targetPort: 3000
