{{- if .Values.controller.serverConfigFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-nginxconf
data:
{{ toYaml .Values.controller.serverConfigFile | indent 2 }}
{{- end }}
