apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: nodes
spec:
  additionalSecurityGroups:
  - EXTRA_NODE_SECURITY_GROUP_ID
  associatePublicIp: false
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: m4.large
  maxSize: 3
  minSize: 3
  role: Node
  rootVolumeSize: 100
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
