apiVersion: batch/v1
kind: Job
metadata:
  name: create-user-home-{{ .Values.Username }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      name: create-user-home
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:16.04
        command: ["/bin/sh", "-c",
          "mkdir -p /homes/home && useradd -u 1001 -g staff -m -d /homes/home/{{ .Values.Username }} {{ .Values.Username }}"]
        volumeMounts:
          - name: homes
            mountPath: "/homes"
      restartPolicy: Never
      volumes:
      - name: homes
        persistentVolumeClaim:
          claimName: nfs-homes
