apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-home-{{ .Values.Username }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: efs
    # volume.beta.kubernetes.io/mount-options: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,ac,async"
  labels:
    mounttype: user
    user: {{ .Values.Username }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.EFSHostname }}
    path: "/users/homes/{{ .Values.Username }}"
