apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-home-{{ .Values.Username }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: efs
  labels:
    mounttype: user
    user: {{ .Values.Username }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.EFSHostname }}
    path: "/home/{{ .Values.Username }}"
