kind: Secret
apiVersion: v1
metadata:
  name: user-secrets
  namespace: user-{{ .Values.Username }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  username: {{ .Values.Username | b64enc | quote }}
  email: {{ .Values.Email | b64enc | quote }}
  fullname: {{ .Values.Fullname | b64enc | quote }}
