image:
  repository: fluent/fluentd-kubernetes-daemonset
  tag: elasticsearch
  pullPolicy: Always
elasticsearch:
  host: elasticsearch-logging
  port: "9200"
  scheme: "http"
  username: ""
  password: ""
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
