apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: jupyter-notebook
        image: xoen/jupyter-notebook:latest
        # Disable authentication, see: https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/README.md#notebook-options
        command: ["start-notebook.sh", "--NotebookApp.token=''"]
        ports:
        - containerPort: 8888
