apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-auth-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-auth-server
    spec:
      containers:
      - name: kubernetes-auth-server
        image: quay.io/djsd123/kube-auth-server:v0.0.1
        imagePullPolicy: Always
        ports:
        - name: app-port
          containerPort: 3000
        env:
          - name: AUTH0_CLIENT_ID
            value:  p4L2qRcSgWyqHjoHanJ4QyhWL1iX612i
          - name: AUTH0_DOMAIN
            value: dev-analytics-moj.eu.auth0.com
          - name: AUTH0_CALLBACK_URL
            value: http://authserver.k8s.dev-analytics-moj/callback
          - name: AUTH0_API_ID
            value: https://dev-analytics-moj.eu.auth0.com/userinfo
          - name: AUTH0_CONNECTION
            value: Username-Password-Authentication
          - name: KUBERNETES_UI_HOST
            value: api.dev.mojanalytics.xyz
          - name: APP_HOST
            value: authserver.dev.mojanalytics.xyz
          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth0-secrets
                key: AUTH0_CLIENT_SECRET
