apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
type: Opaque
data:
  client_secret: {{ .Values.OAuth.ClientSecret | b64enc | quote }}
  client_id: {{ .Values.OAuth.ClientId | b64enc | quote }}
  domain: {{ .Values.OAuth.Domain | b64enc | quote }}
  callback_url: {{ printf "https://%s.%s/callback" .Values.app.name .Values.app.baseHost | b64enc | quote }}
  cookie_secret: {{ .Values.CookieSecret | b64enc | quote }}
