apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  sessionAffinity: ClientIP
  ports:
  - port: {{ .Values.app.port }}
    targetPort: 3000
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
