driver:
  name: terraform
  root_module_directory: "test/fixture"

provisioner:
  name: terraform

platforms:
  - name: aws

verifier:
  name: awspec

suites:
- name: default
  verifier:
    patterns:
    - test/spec/*_spec.rb
