apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
type: Opaque
data:
  client_secret: {{ .Values.auth.clientSecret | b64enc | quote }}
  client_id: {{ .Values.auth.clientID | b64enc | quote }}
  domain: {{ .Values.auth.domain | b64enc | quote }}
  cookie_secret: {{ .Values.auth.cookieSecret | b64enc | quote }}
  kibana_url: {{ printf "http://%s:%s/_plugin/kibana/" .Values.elasticsearch.host .Values.elasticsearch.port | b64enc | quote }}
  callback_url: {{ printf "https://%s/callback" .Values.ingress.host | b64enc | quote }}
