apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:

        - name: jupyter-notebook-auth-proxy
          image: quay.io/mojanalytics/rstudio-auth-proxy:efce8ab3
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: USER
              value: {{.Username}}
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jupyter-notebook-config
                  key: client_secret
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jupyter-notebook-config
                  key: client_id
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: jupyter-notebook-config
                  key: domain
            - name: AUTH0_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: jupyter-notebook-config
                  key: callback_url
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: jupyter-notebook-config
                  key: cookie_secret
            - name: SHINY_HOST
              value: localhost
            - name: SHINY_PORT
              value: "8888"
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: jupyter-notebook
          image: quay.io/mojanalytics/jupyter:f1cd1830430c651bf8d944028e835c5307cddd7a
          # Disable authentication, see: https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/README.md#notebook-options
          command: ["start-notebook.sh", "--NotebookApp.token=''"]
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8888
          env:
            - name: USER
              value: {{.Username}}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: jupyter-notebook-config
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: jupyter-notebook-config
                  key: aws_secret_access_key
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: home
              mountPath: "/home/{{.Username}}"
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: nfs-home
