apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter-notebook
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{.Username}}-jupyter-notebook.{{.ToolsDomain}}
    http:
      paths:
      - backend:
          serviceName: jupyter-notebook
          servicePort: 80
        path: /
