apiVersion: v1
kind: Secret
metadata:
  name: jupyter-notebook-config
type: Opaque
data:
  client_secret: {{.ClientSecretB64}}
  client_id: {{.ClientIDB64}}
  domain: {{.DomainB64}}
  callback_url: {{.CallbackURLB64}}
  cookie_secret: {{.CookieSecretB64}}
  aws_access_key_id: {{.AWSAccessKeyIDB64}}
  aws_secret_access_key: {{.AWSSecretAccessKeyB64}}
