apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  sessionAffinity: ClientIP
  selector:
    app: jupyter-notebook
  ports:
  - port: 80
    targetPort: 3000
