apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-homes
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      mounttype: "root"
  resources:
    requests:
      storage: 100Gi
