apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-homes
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    mounttype: "root"
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.NFSHostname }}
    path: "/users/homes"
