apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: r-studio
  labels:
    app: r-studio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: r-studio
    spec:
      containers:

        - name: rstudio-auth-proxy
          image: quay.io/mojanalytics/rstudio-auth-proxy:0153ad9c
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: USER
              value: {{.Username}}
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: r-studio-config
                  key: client_secret
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: r-studio-config
                  key: client_id
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: r-studio-config
                  key: domain
            - name: AUTH0_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: r-studio-config
                  key: callback_url
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: r-studio-config
                  key: cookie_secret
            - name: SHINY_HOST
              value: localhost
            - name: SHINY_PORT
              value: "8787"
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5

        - name: r-studio-server
          image: quay.io/mojanalytics/rstudio:8a7454fb
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8787
          env:
            - name: USER
              value: {{.Username}}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: r-studio-config
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: r-studio-config
                  key: aws_secret_access_key
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: home
              mountPath: "/home/{{.Username}}"
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: nfs-home
