apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: r-studio
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{.Username}}-rstudio.{{.ToolsDomain}}
    http:
      paths:
      - backend:
          serviceName: r-studio
          servicePort: 80
        path: /
