apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: r-studio
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{.Username}}.rstudio.{{.ToolsDomain}}
    secretName: rstudio-tls
  rules:
  - host: {{.Username}}.rstudio.{{.ToolsDomain}}
    http:
      paths:
      - backend:
          serviceName: r-studio
          servicePort: 80
        path: /
