Username: ""
ToolsDomain: "tools.EXAMPLE.COM"
CookieSecret: ""
OAuth:
  ClientSecret: ""
  ClientId: ""
  Domain: "AUTH0_USER.eu.auth0.com"
AWS:
  AccessKeyId: ""
  SecretAccessKey: ""
  DefaultRegion: "eu-west-1"
Elasticsearch:
  Host: "elasticsearch-server"
  Port: 9200
Fluentd:
  Image:
    Repository: quay.io/fluent/fluentd-kubernetes-daemonset
    Tag: latest
    PullPolicy: "IfNotPresent"
