---
nomis:
    client_id: "your client id"
    client_secret: "your client secret"
    gateway_url: "base url"
    authorize_endpoint: /auth/oauth/authorize
    token_endpoint: /auth/oauth/token
    user_endpoint: /auth/api/user/me
