apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-auth-proxy
  namespace: kube-system
  labels:
    app: kibana-auth-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana-auth-proxy
    spec:
      containers:
        - name: kibana-auth-proxy
          image: quay.io/mojanalytics/kibana-auth-proxy:8cd4eb4c
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kibana-auth-proxy
                  key: client_secret
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: kibana-auth-proxy
                  key: client_id
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: kibana-auth-proxy
                  key: domain
            - name: AUTH0_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: kibana-auth-proxy
                  key: callback_url
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: kibana-auth-proxy
                  key: cookie_secret
            - name: KIBANA_URL
              valueFrom:
                secretKeyRef:
                  name: kibana-auth-proxy
                  key: kibana_url
