apiVersion: v1
kind: Service
metadata:
  name: kibana-auth-proxy
  namespace: kube-system
  labels:
    app: kibana-auth-proxy
spec:
  selector:
    app: kibana-auth-proxy
  ports:
  - port: 80
    targetPort: 3000
