apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-homes
  annotations:
    volume.beta.kubernetes.io/storage-class: efs
  labels:
    mounttype: "root"
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{.EFSHostname}}
    path: "/"
