kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-homes
  annotations:
    volume.beta.kubernetes.io/storage-class: efs
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      mounttype: "root"
  resources:
    requests:
      storage: 100Gi
