apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:593291632749:certificate/1031b54b-778a-4079-acd8-be34310610ee"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  labels:
    app: nginx-ingress-controller
spec:
  type: LoadBalancer
  ports:

  # HTTP directed to nginx server{} block that redirects everything to
  # HTTPS equivalent
  - port: 80
    targetPort: 8000
    name: http

  # HTTPS directed to nginx port 80, as ELB terminates TLS and proxies as HTTP
  - port: 443
    targetPort: 80
    name: https
  selector:
    app: nginx-ingress-controller
