kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-source
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-source
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      mounttype: nfs-source
  resources:
    requests:
      storage: 50Gi
