apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-ops-view
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: opsview.services.alpha.mojanalytics.xyz
    http:
      paths:
      - backend:
          serviceName: kube-ops-view
          servicePort: 80
        path: /
