apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-ops-view
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - opsview.services.dev.mojanalytics.xyz
    secretName: kube-ops-view-tls
  rules:
  - host: opsview.services.dev.mojanalytics.xyz
    http:
      paths:
      - backend:
          serviceName: kube-ops-view
          servicePort: 80
        path: /
