apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    k8s-app: grafana
    task: monitoring
    kubernetes.io/name: monitoring-grafana
  name: grafana-volume
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
