# Master:
#   ServiceType: ClusterIP
#   ContainerPort: 8080
#   SlaveListenerPort: 50000

# Persistence:
#   Enabled: false

# Agent:
#   Image: kerin/jnlp-slave-analytics
#   ImageTag: latest
Master:
  Name: jenkins-master
  Image: kerin/analytics-jenkins
  ImageTag: v2
  ImagePullPolicy: "Always"
  Component: "jenkins-master"
  AdminUser: admin
# AdminPassword: <defaults to random>
  Cpu: "200m"
  Memory: "256Mi"
# Set min/max heap here if needed with:
# JavaOpts: "-Xms512m -Xmx512m"
  ServicePort: 8080
# For minikube, set this to NodePort, elsewhere use LoadBalancer
  ServiceType: ClusterIP
# NodePort: <to set explicitly, choose port between 30000-32767
  ContainerPort: 8080
  SlaveListenerPort: 50000
  LoadBalancerSourceRanges:
  - 0.0.0.0/0

Agent:
  Image: kerin/jnlp-slave-analytics
  ImageTag: latest
  Cpu: "200m"
  Memory: "256Mi"

Persistence:
  Enabled: true
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  AccessMode: ReadWriteOnce
  Size: 10Gi
