apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-home-{{.Username}}
  annotations:
    volume.beta.kubernetes.io/storage-class: efs
  labels:
    mountpoint: "/{{.Username}}"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{.EFSHostname}}
    path: "/{{.Username}}"
